In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np
arr=np.array([10,20,30,40])
print(arr)
#checking version
print(np.__version__)

[10 20 30 40]
1.26.4


In [4]:
arr2=np.array([1,2,3,4,5])
print(arr2)
#array type
print(type(arr2))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
#1 d array
arr2=np.array([10,20,30,40])
print(arr2)

[10 20 30 40]


In [7]:
#2d array
arr3=np.array([[1,2,3],
               [4,5,6]])
print(arr3)              
              

[[1 2 3]
 [4 5 6]]


In [10]:
#array slicing
arr=np.array([20,30,40,50,60,70])
print(arr[1:5:2])
print(arr[-3:-1])

[30 50]
[50 60]


In [16]:
#checking datatype
arr5=np.array([1,2,3,4,5,6])
print(arr5.dtype)

int32


In [17]:
#array shape
arr=np.array([[1,2,3,4],
              [5,6,7,8]])
print(arr.shape)

(2, 4)


In [20]:
#size an array
arr=np.array([[1,2,3,4,],
              [5,6,7,8]])
print(arr.size)

8


In [21]:
#array reshaping
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [22]:
#array lterating
arr=np.array([1,2,3])
for x in arr:
    print(x)

1
2
3


In [23]:
#joining array
arr1=np.array([1,2,3])
aar2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[ 1  2  3 10 20 30 40]


In [25]:
#spliting array
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [26]:
#searching array indexing
arr=np.array([1,2,3,4,5,4,4])
x=np.where(arr==5)
print(x)

(array([4], dtype=int64),)


In [28]:
#soarting array
#assending
arr=np.array([3,2,0,1])
print(np.sort(arr))

[0 1 2 3]


In [29]:
#desending
arr=np.array([3,2,0,1])
print(np.sort(arr)[::-1])

[3 2 1 0]


In [30]:
#filtering array
arr=np.array([41,42,43,44])
x=[True,False,True,False]
newarr=arr[x]
print(newarr)

[41 43]


In [34]:
arr=np.array([41,42,43,44])
filter_arr=[]
for element in arr:
    if element >42:
      filter_arr.append(True)
    else:
        filter_arr.append(False)
newarr=arr[filter_arr]  
print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [35]:
#checking data type of array
arr=np.array([1,2,3,4,5,6])
print(arr.dtype)
#convert the data
print(arr.astype(str))

int32
['1' '2' '3' '4' '5' '6']


In [40]:
#adding and removing
arr=np.array([1,2,3,4,5,6])
#adding only ending
print(np.append(arr,[6,7]))
#insert(adding into specific element)
print(np.insert(arr,3,[6,7]))
#delete
print(np.delete(arr,[1]))

[1 2 3 4 5 6 6 7]
[1 2 3 6 7 4 5 6]
[1 3 4 5 6]


In [44]:
#agrigate function
arr=np.array([10,20,30,40,50])
#sum
print(np.sum(arr))
#minimum
print(np.min(arr))
#maximum
print(np.max(arr))
#comsum


150
10
50


In [48]:
#statistical function
import statistics as stats
food_prices=[10,20,30,40,50,60,70]
a=np.array(food_prices)
#mean
print(np.mean(a))
#median
print(np.median(a))
#mode
print(stats.mode(a))

40.0
40.0
10
